spring:
  application:
    name: gateway-service
    
server:
  port: ${PORT:5555}

eureka:  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - routes
        - info
        - health