spring:
  application:
    name: gateway-service
    
server:
  port: 5555

eureka:  
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: 80